name: Windows EXE Build

on:
  push:
    branches: [ main ]  # Or whichever branch you're using
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      SUPABASE_JDBC_URI: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.dynoojyjpzpneoclqbdh&password=s9rcjWBy6JX6kqEU
      OPENROUTER_API_KEY: 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

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Use your version here

      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/24/openjfx-24_windows-x64_bin-sdk.zip
          tar -xf javafx.zip
          move javafx-sdk-24 lib\javafx

      - name: Set up WiX Toolset
        run: choco install wixtoolset -y

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Generate .env file
        run: |
          echo SUPABASE_JDBC_URI=$env:SUPABASE_JDBC_URI > target/.env
          echo OPENROUTER_API_KEY=$env:OPENROUTER_API_KEY >> target/.env

      - name: Package with jpackage
        run: |
          jpackage ^
            --type exe ^
            --name ChronoPanthers ^
            --input target ^
            --main-jar ChronoPanthers-1.0-SNAPSHOT.jar ^
            --main-class com.example.chronopanthers.ChronoPanthers ^
            --java-options "--module-path lib\javafx\lib --add-modules javafx.controls,javafx.fxml" ^
            --dest dist ^
            --icon src\main\resources\cp.ico ^
            --app-version 1.0 ^
            --verbose

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: ChronoPanthers-Installer
          path: dist/*.exe
